- name: Build ISO
  uses: jasonn3/build-container-installer@main
  id: build
  with:
    arch: ${{ x86_64 }}
    image_name: ${{ baryte-os }}
    image_repo: ${{ ghcr.io/betim-hodza }}
    image_tag: ${{ latest }}
    version: ${{ 1.0 }}
    variant: ${{ desktop }}
    iso_name: ${{ baryte-os }}-${{ latest }}-${{ 1.0 }}.iso

- name: Upload ISO as artifact
  id: upload
  uses: actions/upload-artifact@v4
  with:
    name: ${{ steps.build.outputs.iso_name }}
    path: |
      ${{ steps.build.outputs.iso_path }}
      ${{ steps.build.outputs.iso_path }}-CHECKSUM
    if-no-files-found: error
    retention-days: 0
    compression-level: 0

